# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='userName', max_length=32)),
                ('password', models.CharField(db_column='passWord', max_length=32)),
                ('url_login', models.CharField(db_column='url_login', max_length=200)),
            ],
        ),
    ]
